const quoteData = {
  quote_number: "ENV-2026-002",
  date: "19-03-2026",
  valid_until: "07-04-2026",

  from: {
    company: "Envoya",
    legal: "Propio Negocio B.V.",
    address: "Bronsbergen 22, 7207 AA Zutphen",
    kvk: "KvK 56248482",
    btw: "BTW NL852039839B02",
    email: "admin@envoya.tech"
  },

  to: {
    company: "Elision BV",
    contact: "Olivier Tahey",
    email: ""
  },

  package_title: "Lead Machine — Complete Package",
  package_subtitle: "Your AI sales agent, installed and ready to run.",

  line_item: {
    description: "Lead Machine — Complete Package",
    includes: "Apple Mac Mini M4 Pro, lifetime license (3 users, all future updates), ICP build on your company data, first campaign configured and ready to send, 3-hour live onboarding, 30-day post-launch support, and results guarantee.",
    qty: 1,
    unit_price: 20661,
    vat: 0.21
  },

  included_items: [
    {
      title: "Apple Mac Mini M4 Pro",
      desc: "Dedicated local AI agent running 24/7 at your office"
    },
    {
      title: "Lifetime license — 3 users",
      desc: "All future updates included, no renewal, no monthly fees"
    },
    {
      title: "ICP build on your company data",
      desc: "Model trained on your client history, deals and target sectors"
    },
    {
      title: "First campaign configured",
      desc: "Lead list, email sequence and targeting ready on day 1"
    },
    {
      title: "3-hour live onboarding",
      desc: "Your team up and running independently after one session"
    },
    {
      title: "30-day post-launch support",
      desc: "Direct response within 24 hours after go-live"
    }
  ],

  guarantee: {
    title: "Results Guarantee — included at no charge",
    text: "If you send the daily emails generated by the system and book fewer than 5 meetings in the first 30 days, we come back for a full campaign revision. In person. Free. No questions asked."
  },

  expectation: {
    title: "What we expect from you",
    text: "Lead Machine works when you send the daily generated emails and handle the follow-ups. On average 45 minutes per day. You run the conversations. We fill your calendar."
  },

  footer_note: "Lifetime license is personal and non-transferable without written consent from Envoya."
}
